[package]
name = "sourisdb"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
proptest = "1.4.0"

[dependencies]
chrono = "0.4"
hashbrown = "0.14"
serde = {version = "1.0", optional = true, features = ["derive"]}
serde_json = "1.0.116"

[features]
default = []
std = []
serde = ["dep:serde", "chrono/serde", "hashbrown/serde"]
